[project]
name = "perplexicat"
version = "0.1.0"
description = "Perplexity-like self-hosted interface for SearXNG"
readme = "README.md"
requires-python = ">=3.14"
license = { file = "LICENSE" }
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "flask>=3.1.2",
    "flask-login>=0.6.3",
    "flask-sqlalchemy>=3.1.1",
    "requests>=2.32.5",
    "werkzeug>=3.1.5",
]

[dependency-groups]
dev = [
    "ruff>=0.14.13",
    "ty>=0.0.13",
]
